language: rust
cache: cargo
install:
- rustup component add rustfmt
script:
- cargo fmt -- --check
- cargo build --verbose --all-features
- export RUST_BACKTRACE=full
- cargo test --verbose --all-features -- --nocapture
deploy:
  provider: cargo
  token:
    secure: mS24CEmLokcSIEu4Xn78NX0Sd5bJAVgdQLtWiPvrMY9FPYjMmLAeUPcGjassCVb/+Qo89GyLfaHPHLhtEY0Z2WjQizQ85jjzVh/gJv/tYzbbYyqI1AFQYWqYSM+lFZhNy0wQRfw+6CFoAlcH1vQc5q5+2fTnSK+eRqEB1+Nne+ht6Rha8AqWwqXg/krgMMhTui8rSlrdDxYo/M2NTzW46oa5gztRkDfke5G0wv//25rRP4Wqug4v+Zir/6GvWAUXJxh47DiYKv3BO0yM25pnXdDBPT21KEBXzh3cJx6+7sW5fprXE3CKfTj0dZW/1tYIi0YxJOLLCA2zIPgKio8L3mpQyg05Xvoahh4Anl1YCI4+fWc29cnyx3Kqr7KRUSxyTqacO/EYdo5m0G7wN5WiNPoiwyzZjMkhe+wVw45My7ZhxkFyOn3tXzTybCcSy8o46yiKK46yYOsjfx7xtkBGrb9n3ByFsCdZD38bBNtemQhxYeL3bXGzI4zYo6IiuSRyBviooGo2JpvhYaJv6qeUf41q4AdqUnpKP21p+1aDNzvmo4pGnoPXHA3Y+DhUcfJWiNppxbsLFUXwNvH3O7einIinBJw3cT6SILjAivxS5Sj0NTWAdR20x20ATk7DXOcSX0PwKFqMbOTWMQhRiQLSdEYqTx/VibXZECrJZ8XewE8=
  on:
    tags: true
  cleanup: true
  allow_dirty: true

