[package]
name = "mavlink"
version = "0.3.1"
authors = ["Tim Ryan <tim@3dr.com>"]
build = "build/main.rs"
description = "Parses the MAVLink data interchange format for UAVs."
license = "MIT"

[build-dependencies]
crc16 = "0.3.3"
byteorder = "0.5.3"
xml-rs = "0.2"

[[bin]]
name = "mavlink-dump"

[dependencies]
crc16 = "0.3.3"
byteorder = "0.5.3"
log = "0.3.6"
env_logger  = "0.3.3"
