[package]
name = "mavlink"
version = "0.3.1"
authors = ["Tim Ryan <tim@3dr.com>"]
build = "build/main.rs"
description = "Parses the MAVLink data interchange format for UAVs."
license = "MIT"

[build-dependencies]
bytes = "0.2.11"
crc16 = "0.3.3"
byteorder = "0.4.2"
xml-rs = "0.2"

[[bin]]
name = "mavlink-dump"

[dependencies]
mio = "0.5"
bytes = "0.2.11"
crc16 = "0.3.3"
byteorder = "0.4.2"
time = "0.1"
bit-vec = "0.4.2"
eventual = "0.1.5"
chan = "0.1.17"
